"""Verify stored primer reverse-complements against computed RCs.

The original constants.py comment noted the RC values were generated by a
web tool and hand-pasted. This computes the RC from the primer sequence
(with full IUPAC degenerate-base support) and asserts a match, so any
fat-fingered constant fails immediately rather than silently mis-trimming reads.
"""

import pytest

from tag_analysis import constants
from tag_analysis.config import PRIMERS_16S, PRIMERS_18S

# IUPAC nucleotide complement map (includes degenerate codes present in these primers).
_IUPAC_COMPLEMENT = {
    "A": "T", "T": "A", "G": "C", "C": "G",
    "R": "Y", "Y": "R", "S": "S", "W": "W",
    "K": "M", "M": "K", "B": "V", "V": "B",
    "D": "H", "H": "D", "N": "N", "U": "A",
}


def reverse_complement(seq: str) -> str:
    """Reverse complement of an IUPAC nucleotide string."""
    return "".join(_IUPAC_COMPLEMENT[b] for b in reversed(seq.upper()))


@pytest.mark.parametrize("primers", [PRIMERS_16S, PRIMERS_18S], ids=["16S", "18S"])
def test_fwd_rc_matches_computed(primers):
    assert primers.fwd_rc == reverse_complement(primers.fwd), (
        f"{primers.name} FWD_RC does not match RC of FWD "
        f"({primers.fwd!r} -> expected {reverse_complement(primers.fwd)!r}, "
        f"stored {primers.fwd_rc!r})"
    )


@pytest.mark.parametrize("primers", [PRIMERS_16S, PRIMERS_18S], ids=["16S", "18S"])
def test_rev_rc_matches_computed(primers):
    assert primers.rev_rc == reverse_complement(primers.rev), (
        f"{primers.name} REV_RC does not match RC of REV "
        f"({primers.rev!r} -> expected {reverse_complement(primers.rev)!r}, "
        f"stored {primers.rev_rc!r})"
    )


def test_reverse_complement_is_involution():
    """RC(RC(x)) == x for a plain sequence, sanity-checking the helper itself."""
    seq = "GTGYCAGCMGCCGCGGTAA"
    assert reverse_complement(reverse_complement(seq)) == seq


def test_primer_sets_distinct():
    assert PRIMERS_16S.fwd != PRIMERS_18S.fwd
    assert constants.RANKS[0] == "domain" and constants.RANKS[-1] == "species"
